dataset:
  data_dir: ../../data_demo
  history_size: 30
  max_title_length: 30
model:
  hidden: 768
  pretrained_model_name: bert-base-uncased
train:
  batch_size: 32
  num_epochs: 30
  learning_rate: 0.001
ckp_dir: checkpoints