#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=O_MAIN
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=06:00:00
#SBATCH --output=./results/slurm_logs/slurm_ONLY_MAIN_%A.out


cd $HOME/RecSys/

# Source the .bashrc to initialize conda for the current session
source $HOME/.bashrc

# Activate env
conda activate recsys_JE

# Run python
python3 src/mtrec/train_mtrec.py --file 3_Only_MAIN
