#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=O_CAT
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=06:00:00
#SBATCH --output=./results/slurm_logs/slurm_ONLY_CAT_%A.out


cd $HOME/RecSys/

# Source the .bashrc to initialize conda for the current session
source $HOME/.bashrc

export PATH=$HOME/miniconda3/bin:$PATH


# Activate env
conda activate recsys

# Run python
python3 src/mtrec/train_mtrec.py --file 5_Only_Cat
