#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=env_install
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:20:00
#SBATCH --output=./results/slurm_logs/slurmenv_install_%A.out


cd $HOME/RecSys/

# Source the .bashrc to initialize conda for the current session
source $HOME/.bashrc

# install env
conda activate recsys
# conda install -c conda-forge optuna
# conda install peft
pip install ebrec 