dataset:
  data_dir: ../../data_demo
  history_size: 30
  max_title_length: 30
  batch_size: 32
  npratio: 4
  dataset_fraction: 0.01
model:
  hidden: 768
  pretrained_model_name: bert-base-uncased
train:
  num_epochs: 30
  learning_rate: 0.001
ckp_dir: checkpoints