name_run: Hypertuning

max_val_bs: 64

news_encoder:
  cfg_cat:
    num_layers: 2
    hidden_size: 124
    output_size: 33 #TODO JE: make dynamic based on the dataset
  cfg_ner:
    num_layers: 2
    hidden_size: 124
    output_size: 3 #TODO JE: make dynamic based on the dataset
    extend_output_size: 7

user_encoder:
  hidden_size: 128

trainer:
  aux_scaler: 0.3
  optimizer: adamw
  epochs: 3
  lr_user: 0.001
  lr_news: 0.001
  lr_bert: 0.00001
  batch_size: 64
  skip_ner: False
  skip_cat: False
  skip_gs: False

dataset:
  data_dir: data_small
  history_size: 20
  max_title_length: 30
  npratio: 4
  dataset_fraction: 0.001
  testset_fraction: 0.002
  extended_NER: False

model:
  hidden: 768
  pretrained_model_name: bert-base-multilingual-uncased

lora_config:
  r: 8  # Rank of the decomposition
  lora_alpha: 32  # Scaling factor
  target_modules:
    - "query"
    - "value"  # Targeted modules in BERT
  lora_dropout: 0.1  # Dropout rate
  bias: "none"  # Bias type 

hypertuning:
  hidden_size: [64, 128, 256, 512]
  num_layers:
    min: 1
    max: 3
  batch_size: [8,16,32]
  lr:
    min: 1e-06
    max: 5e-03
  optimizer: [adam, adamw, sgd]
  n_trials: 150

wandb: True