news_encoder:
  cfg_cat:
    num_layers: 2
    hidden_size: 124
    output_size: 25
  cfg_ner:
    num_layers: 2
    hidden_size: 124
    output_size: 3

user_encoder:
  hidden_size: 128
trainer:
  optimizer: adamw
  epochs: 2
  lr_user: 0.001
  lr_news: 0.001
  lr_bert: 0.0001
  batch_size: 2

dataset:
  data_dir: data_demo
  history_size: 15
  max_title_length: 20
  npratio: 4
  dataset_fraction: 0.01

model:
  hidden: 768
  pretrained_model_name: bert-base-multilingual-uncased

lora_config:
  r: 8  # Rank of the decomposition
  lora_alpha: 32  # Scaling factor
  target_modules:
    - "query"
    - "value"  # Targeted modules in BERT
  lora_dropout: 0.1  # Dropout rate
  bias: "none"  # Bias type 

wandb: True